#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=models
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=10:00:00
#SBATCH --output=slurm_outputs/VAST/download_vast_pretrained_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

# Activate your environment
source activate triangle

cd $HOME/VAST

# Download vast_pretraining checkpoint
srun python /gpfs/home5/scur1713/scripts/download_vast_model.py --base_dir .