#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=models
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=15:00:00
#SBATCH --output=slurm_outputs/normalize_didemo_filenames_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

# Activate your environment
source activate triangle

cd $HOME/TRIANGLE

# Rename didemo audio and video
srun python /gpfs/home5/scur1713/scripts/normalize_didemo_filenames.py