#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=models
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=10:00:00
#SBATCH --output=slurm_outputs/unzip_triangle_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

# Activate your environment
source activate triangle

cd $HOME/TRIANGLE

UNZIP_DISABLE_ZIPBOMB_DETECTION=TRUE unzip triangle_pretraining.zip